### PR TITLE
DC-1344: Added Email search logic.

### PR DESCRIPTION
**Pull request by rambabu-posa**

### CODE REVIEW

**Comment by sudoku007** [comment]
If the search results in more than 1 user record, you are not showing the `Opt Out` actions in the use summary details page. So admin cannot `Opt Out` users.

Tests need to be updated to reflect assertion of this behaviour, at the moment there are not tests which are verifying this behaviour for search by email id.

**Comment by sudoku007** [comment]
When you search an email id which does not exists, it is returning 404 error instead of showing no showing no preferences found on the GUI.

**Comment by rambabu-posa** [comment]
Regarding first point, yes thats correct behaviour. We should not show `Opt Out `actions for multiple search results. We should show it only for one record.

**Comment by sudoku007** [comment]
Existing behaviour is not working, when we search by a SaUtr or Nino which does not exists, instead of showing the error preferences not found, it is showing a blank page.  

Looks like the test scenario's are not covering these scenarios as they should have failed, we need to update tests to cover these scenarios.

**Comment by rambabu-posa** [comment]
Last point is correct, I missed couple of changes to push to this pr

**Comment by rambabu-posa** [comment]
@sudoku007: Please review it now

**Pull request merged**
